generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardUser
    theme:                 twitter
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_user
    with_propel_route:     1

    config:
      fields:
        password_again: { label: Repita contraseña }
        is_active: {label: Activo}
        username: {label: Usuario}
        apeynom: {label: Apellido y nombre}
        dni: {label: DNI}
        is_super_admin: {label: Administrador}

      list:
        title:   Usuarios
        display: [=username, apeynom, dni]
        batch_actions: {}
        object_actions: {_edit: ~, "verAccesos": {label: Ver Accesos, icon: icon-th}, _delete: ~}

      form:
        class: sfGuardUserAdminForm
        actions: {_list: ~, _save: ~}
        display:
          "NONE":                   [username, password, password_again]
          "Permisos":               [is_active, is_super_admin, sf_guard_user_group_list]
          "Perfil":                 [apeynom, dni]

      edit:
        title: Editando usuario "%%username%%"

      new:
        title: Nuevo Usuario