crear_usuario:
  url: /sf_guard_user/crearUsuario
  param: {module: sf_guard_user, action: crearUsuario}
  
actualizar_usuario:
  url: /sf_guard_user/actualizarUsuario
  param: {module: sf_guard_user, action: actualizarUsuario}
  
baja_usuario:
  url: /sf_guard_user/bajaUsuario
  param: {module: sf_guard_user, action: bajaUsuario}
# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

acceder_producto:
  url: /a/:producto
  param: {module: inicio, action: accesoDirecto}

# default rules
homepage:
  url:   /
  param: { module: inicio, action: index }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
