generator:
  class: sfPropelGenerator
  param:
    model_class:           sfGuardGroup
    theme:                 twitter
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          sf_guard_group
    with_propel_route:     1

    config:
      fields:
        name: {label: Nombre corto}
        description: {label: Descripción}
        
      list:
        title: Roles
        display: [=name, description]
        batch_actions: {}

      edit:
        title: Rol "%%name%%"

      new:
        title: Nuevo rol
